name: test

on: push

jobs:
  job1:
    runs-on: ubuntu-lastest

    steps:
      - uses: actions/checkout@v2
      - name: run a shell script
        run: echo hello from me

  job2:
    runs-on: ubuntu-lastest

    steps:
      - uses: actions/checkout@v2
      - name: run a shell script
        run: echo world from me
